-- Equity Terms table for the Equity Term Explainer feature
CREATE TABLE IF NOT EXISTS equity_terms (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  term TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  definition TEXT NOT NULL,
  example TEXT NOT NULL,
  common_mistake TEXT NOT NULL,
  why_it_matters TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('Basics', 'Options', 'Tax', 'Vesting', 'Valuation', 'Negotiation')),
  related_terms TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Index for fast slug lookups
CREATE INDEX IF NOT EXISTS idx_equity_terms_slug ON equity_terms(slug);
CREATE INDEX IF NOT EXISTS idx_equity_terms_category ON equity_terms(category);

-- Enable RLS
ALTER TABLE equity_terms ENABLE ROW LEVEL SECURITY;

-- Public read access (terms are educational, no auth required)
CREATE POLICY "equity_terms_public_read" ON equity_terms
  FOR SELECT USING (true);

-- Seed with 50 real equity terms
INSERT INTO equity_terms (term, slug, definition, example, common_mistake, why_it_matters, category, related_terms) VALUES
('Stock Options', 'stock-options', 'A contract that gives you the right to buy shares in a company at a fixed price (the strike price) within a certain time frame. Stock options are not shares themselves — they are the right to purchase shares later.', 'You receive an offer granting 10,000 stock options with a strike price of $1.00. If the company later reaches a $10 share price, you can exercise your options to buy shares at $1 each, making $9 per share in paper profit.', 'Treating stock options as if you already own shares. You own nothing until you exercise (buy). Options can expire worthless if the company share price never exceeds your strike price.', 'Stock options are the most common form of startup equity compensation. Understanding them is the foundation for making informed decisions about your total compensation.', 'Basics', ARRAY['iso', 'nso', 'strike-price', 'exercise-window', 'vesting']),

('Incentive Stock Options (ISOs)', 'iso', 'A type of stock option that qualifies for favorable tax treatment under IRS rules. ISOs are only available to employees. If you meet holding requirements — hold shares for 2 years from grant and 1 year from exercise — profit is taxed at long-term capital gains rates.', 'You exercise 5,000 ISOs at $2 strike when FMV is $10. If you hold for the required periods, you pay 15-20% capital gains tax on the $40,000 profit instead of 22-37% ordinary income tax.', 'Forgetting about AMT. When you exercise ISOs, the spread between strike price and FMV is an AMT preference item. Many employees get a surprise tax bill even though they received no cash.', 'ISOs can save tens of thousands in taxes if managed correctly. But the AMT trap catches many people off guard.', 'Options', ARRAY['stock-options', 'nso', 'amt', 'strike-price', 'capital-gains']),

('Non-Qualified Stock Options (NSOs)', 'nso', 'Stock options that do not qualify for ISO tax treatment. NSOs can be granted to employees, contractors, advisors, and board members. The spread at exercise is taxed as ordinary income.', 'You exercise 5,000 NSOs at $2 strike when FMV is $10. The $40,000 spread is ordinary income — your company withholds income tax, Social Security, and Medicare.', 'Assuming NSOs are always worse than ISOs. For employees at companies where strike and FMV are close, the tax difference may be minimal. NSOs also avoid the AMT trap.', 'Most options granted to non-employees are NSOs, and even employees often receive NSOs for grants exceeding the $100K ISO limit.', 'Options', ARRAY['stock-options', 'iso', 'strike-price', 'exercise-window']),

('Restricted Stock Units (RSUs)', 'rsu', 'A promise to give you shares of company stock on a future date once vesting conditions are met. Unlike options, RSUs have no strike price — you receive full shares. At private companies, RSUs often require both vesting and a liquidity event.', 'Google grants you 400 RSUs vesting over 4 years. Each quarter, 25 shares vest and are deposited into your brokerage account, taxed as ordinary income.', 'Not accounting for taxes at vesting. Most companies sell a portion of shares to cover withholding, so you receive fewer shares than granted. A 400 RSU grant might net ~260 shares.', 'RSUs are the dominant equity form at large tech companies. They always have value as long as the stock price is above $0.', 'Basics', ARRAY['restricted-stock', 'vesting', 'double-trigger', 'capital-gains']),

('Restricted Stock', 'restricted-stock', 'Actual shares granted immediately but with restrictions — typically a vesting schedule. If you leave before vesting, the company can repurchase unvested shares. Different from RSUs: you own shares from day one.', 'A co-founder receives 1,000,000 shares at $0.001/share with 4-year vesting. They file an 83(b) election within 30 days, paying ~$100 in taxes. All future gains are long-term capital gains.', 'Failing to file an 83(b) election within 30 days. Without it, you are taxed on share value as they vest, which could be millions. There is no extension.', 'Combined with an 83(b) election, restricted stock offers the best possible tax treatment for startup equity.', 'Basics', ARRAY['rsu', '83b-election', 'vesting', 'repurchase-rights']),

('Vesting', 'vesting', 'The process of earning ownership of equity over time. The most common schedule: 4 years with 1-year cliff — nothing for year 1, then 25% vests at the cliff, remaining 75% monthly over 3 years.', 'You are granted 48,000 options with 4-year monthly vesting and 1-year cliff. After 12 months, 12,000 vest at once. Then 1,000 vest each month for 36 months.', 'Confusing granted with vested. Being granted 100,000 options means nothing until they vest. Leave after 6 months with a 1-year cliff = zero equity.', 'Vesting determines when you actually own what you were promised. It is the most important timeline in your equity compensation.', 'Vesting', ARRAY['cliff', 'acceleration', 'stock-options', 'rsu']),

('Cliff', 'cliff', 'A mandatory waiting period before any equity vests. Standard is 1 year. During the cliff, zero shares vest. Once past the cliff date, a large chunk (usually 25%) vests at once.', 'You start January 1, 2025 with a 1-year cliff. Quit December 15, 2025 = zero equity. Stay until January 1, 2026 = 25% of your grant vests immediately.', 'Not negotiating the cliff. If a company is well-established, a 1-year cliff may be unnecessary. Some candidates negotiate shorter cliffs or immediate partial vesting.', 'The cliff is a trial period for equity. Your first year is the riskiest: you work with zero equity safety net.', 'Vesting', ARRAY['vesting', 'acceleration', 'stock-options']),

('Acceleration', 'acceleration', 'A provision that speeds up vesting when certain events occur. Single-trigger: accelerates on one event (acquisition). Double-trigger: requires two events (acquisition AND termination). Can be full or partial.', 'Your offer includes double-trigger acceleration. Company is acquired (trigger 1), you are laid off 3 months later (trigger 2). All unvested shares vest immediately.', 'Assuming all acceleration provisions are the same. Single-trigger is much more valuable but rarer. Many offers include no acceleration at all.', 'Without acceleration, an acquisition can harm employees. The acquirer can terminate you and you lose unvested equity.', 'Vesting', ARRAY['double-trigger', 'single-trigger', 'change-of-control', 'vesting']),

('Strike Price', 'strike-price', 'The fixed price at which you can buy shares when exercising stock options. Set at Fair Market Value on the grant date. Lower strike = greater potential profit.', 'You join when FMV is $0.50/share. Two years later the company raises at $20/share. Exercise at $0.50 for $19.50/share paper profit.', 'Thinking a low strike price guarantees profit. The strike only matters if the share price exceeds it. If the company fails, options are worthless regardless.', 'Strike price determines your break-even point. Joining earlier means lower strike price and more upside — but also more risk.', 'Options', ARRAY['fmv', '409a-valuation', 'stock-options', 'exercise-window']),

('Fair Market Value (FMV)', 'fmv', 'The current estimated value of one share, determined by independent appraisal for private companies (409A valuation) or stock price for public companies. Used to set strike prices and calculate taxes.', 'A startup 409A sets FMV at $1.50/share. When the company raises Series B at $5/share preferred, common stock FMV might be $2.00 due to liquidation preference discount.', 'Confusing common stock FMV with the fundraising price. The fundraise reflects preferred stock with extra rights. Common stock FMV is typically 60-80% lower.', 'FMV affects strike price, taxes, and equity value. Common stock FMV differs from headline fundraising numbers.', 'Valuation', ARRAY['409a-valuation', 'strike-price', 'preferred-stock', 'common-stock']),

('409A Valuation', '409a-valuation', 'An independent appraisal of a private company common stock FMV, required by IRS Section 409A. Companies must get one at least annually to set compliant option strike prices. Non-compliant options trigger severe tax penalties.', 'A startup raises Series A at $10/share preferred. The 409A firm assesses common stock at $3/share. All options granted after use $3 as strike price.', 'Thinking a low 409A is always good. While it means a lower strike price, it also signals assessors see significant risk. An unusually low 409A may indicate structural issues.', '409A valuations directly determine your strike price and protect both you and the company from IRS penalties.', 'Valuation', ARRAY['fmv', 'strike-price', 'section-409a', 'stock-options']),

('Alternative Minimum Tax (AMT)', 'amt', 'A parallel tax system triggered when exercising ISOs. The spread (FMV minus strike) is an AMT preference item, potentially creating a tax bill even though you received no cash and sold no shares.', 'You exercise 20,000 ISOs at $1 strike when FMV is $15. The $280,000 spread triggers AMT. You may owe $50-80K in taxes with no cash income. If the stock drops, you still owe the AMT.', 'Exercising a large batch of ISOs without calculating AMT first. Many people get stuck when the company has no liquidity event to fund their tax bill.', 'AMT is the single biggest financial risk for startup employees with ISOs. People have lost homes over unexpected AMT bills.', 'Tax', ARRAY['iso', '83b-election', 'capital-gains', 'early-exercise']),

('Capital Gains Tax', 'capital-gains', 'Tax on profit from selling an asset. Short-term (held <1 year): ordinary income rates (22-37%). Long-term (held >1 year): preferential rates (0%, 15%, or 20%). The holding period starts at exercise for options.', 'You exercise ISOs at $2, sell a year later at $20. If holding period requirements are met, the $18/share gain is taxed at 15-20% instead of 22-37%.', 'Selling immediately after exercise expecting long-term rates. For ISOs: hold 1 year after exercise AND 2 years after grant. Otherwise it is ordinary income.', 'The long-term vs short-term difference can be 15-20% of your total profit. On $200K gain, that is $30-40K in savings.', 'Tax', ARRAY['iso', 'nso', 'amt', '83b-election']),

('83(b) Election', '83b-election', 'A tax election filed with the IRS within 30 days of receiving restricted stock. Pay taxes on current value instead of future vested value. All future appreciation taxed at long-term capital gains rates.', 'Co-founder receives 1M shares at $0.001/share. Files 83(b), pays ~$100 in taxes. At $50/share exit, $49,999,000 gain taxed at long-term capital gains (~15-20%) instead of ordinary income (~37%).', 'Missing the 30-day deadline. No extension, no exception. Also: cannot file 83(b) for RSUs or stock options — only restricted stock or early-exercised options.', 'The 83(b) election is the most powerful tax tool for founders and early employees. Filing a $100 form within 30 days can save millions.', 'Tax', ARRAY['restricted-stock', 'early-exercise', 'capital-gains', 'iso']),

('Dilution', 'dilution', 'The reduction in your ownership percentage when the company issues new shares. Every fundraise, option pool expansion, or conversion creates new shares. Your share count stays the same but you own a smaller slice.', 'You own 100,000 of 10M shares (1%). Company issues 5M new shares. You still own 100,000 but now of 15M total — your ownership dropped from 1% to 0.67%.', 'Panicking about dilution without considering valuation. If ownership drops from 1% to 0.5% but the company is worth 10x more, your equity is worth 5x what it was.', 'Every startup employee will experience dilution. Track both percentage ownership and dollar value.', 'Valuation', ARRAY['anti-dilution', 'cap-table', 'fully-diluted-shares', 'option-pool']),

('Anti-Dilution', 'anti-dilution', 'A protection clause for investors that adjusts their share price downward if the company raises at a lower valuation (down round). Common types: full ratchet and weighted average. Employees do not get this protection.', 'Investor buys at $10/share with weighted-average anti-dilution. Down round at $5/share adjusts investor conversion to ~$7.50/share. Common stockholders bear the additional dilution.', 'Thinking anti-dilution protects everyone. It protects investors at the expense of common stockholders. In a down round, employees can see ownership crushed more than investors.', 'Anti-dilution determines who bears the pain in a down round. As an employee, this tells you how exposed you are if the company stumbles.', 'Valuation', ARRAY['dilution', 'preferred-stock', 'cap-table', 'liquidation-preference']),

('Cap Table', 'cap-table', 'Short for capitalization table — the definitive record of who owns what. Tracks all share classes, option grants, warrants, and convertible instruments. The ground truth of equity.', 'A Series B cap table: Founders 50% common, Series A 20% preferred, Series B 15% preferred, option pool 15% (800K granted, 700K unallocated).', 'Not asking to see the cap table before accepting an offer. Without it, knowing you have 10,000 shares is meaningless. You need total shares outstanding and the preference stack.', 'The cap table is the ground truth. Your offer letter says how many shares; the cap table says what they are worth.', 'Valuation', ARRAY['fully-diluted-shares', 'dilution', 'preferred-stock', 'option-pool']),

('Liquidation Preference', 'liquidation-preference', 'Investors right to get paid before common stockholders in an exit. 1x non-participating: investors get money back first. 2x: double their investment first. Participating: get preference AND share in remainder.', 'Investors put in $50M with 1x non-participating preference. Company sells for $80M. Investors take $50M. Remaining $30M split among common stockholders. At $40M exit: investors take all, common gets nothing.', 'Ignoring preferences when valuing equity. If $100M in preferences, the first $100M of any exit goes to investors. Common stock only has value above that threshold.', 'Liquidation preference is the single most important concept for understanding what your equity is actually worth in an exit.', 'Valuation', ARRAY['preferred-stock', 'common-stock', 'cap-table', 'anti-dilution']),

('Preferred Stock', 'preferred-stock', 'A stock class with special rights: liquidation preference, anti-dilution, dividend rights, sometimes board seats. This is what investors receive. It sits above common stock in the payment hierarchy.', 'A VC invests $20M in Series B preferred at $10/share. Their shares have 1x liquidation preference, anti-dilution, a board seat, and pro-rata rights.', 'Using preferred stock price to value common shares. If Series B is $10/share, common stock is NOT $10/share due to missing protections. Common is typically 60-80% less.', 'The preferred vs common distinction is why headline valuations mislead employees about their equity value.', 'Basics', ARRAY['common-stock', 'liquidation-preference', 'anti-dilution', 'cap-table']),

('Common Stock', 'common-stock', 'The most basic stock class. What founders, employees, and option holders receive. Has voting rights but sits below preferred stock in payment hierarchy. Paid last in liquidation events.', 'You exercise 10,000 common shares. In a $100M acquisition after $60M in preferences, you share in the remaining $40M proportionally.', 'Assuming common stock equals preferred stock in value. In modest exits, common can be worth significantly less than preferred — or worth nothing.', 'As an employee you hold common stock. It has different economics than investor shares. This is essential for realistic valuation.', 'Basics', ARRAY['preferred-stock', 'liquidation-preference', 'cap-table', 'fmv']),

('Exercise Window', 'exercise-window', 'The time to exercise vested options. While employed: typically 10 years. After leaving: most agreements give just 90 days (the "golden handcuffs" problem). Some companies offer 1-10 year extended windows.', 'You leave with 50,000 vested options at $2 strike, FMV $15. You have 90 days to find $100,000+ cash plus taxes. Cannot afford it? Lose everything.', 'Not factoring the exercise window into offer evaluation. A 90-day window can force a terrible choice: hundreds of thousands in cash within 3 months, or forfeit years of equity.', 'The 90-day window is one of the most employee-hostile provisions. Companies like Coinbase and Quora adopted 7-10 year windows. Negotiate this.', 'Options', ARRAY['stock-options', 'strike-price', 'cashless-exercise', 'early-exercise']),

('Cashless Exercise', 'cashless-exercise', 'Exercising options without paying out of pocket. A broker simultaneously exercises options and sells enough shares to cover the cost and taxes. Only works with liquid stock (public companies or during tender offers).', 'You have 10,000 options at $5 strike, stock at $50. Broker exercises all, sells 1,200 shares to cover costs, deposits 8,800 shares.', 'Expecting cashless exercise at a private company. It requires a liquid market. At startups, you need actual cash to exercise.', 'Cashless exercise eliminates the biggest barrier at public companies. At private companies, plan for the full cash outlay.', 'Options', ARRAY['exercise-window', 'stock-options', 'strike-price', 'tender-offer']),

('Early Exercise', 'early-exercise', 'The ability to exercise options before they vest. You buy shares immediately at the current strike price, subject to company repurchase until they vest. Paired with 83(b) election for optimal tax treatment.', 'You join at founding with 100,000 options at $0.01 strike. Early exercise all for $1,000, file 83(b). At $50/share exit, entire gain taxed at long-term capital gains.', 'Early exercising without filing 83(b) within 30 days. Also, if the company fails, you lose the money paid. Only early exercise when the cost is affordable to lose.', 'Early exercise + 83(b) is the gold standard for tax optimization at early-stage startups. Only practical when strike is very low.', 'Options', ARRAY['83b-election', 'stock-options', 'strike-price', 'restricted-stock']),

('Tender Offer', 'tender-offer', 'A company-organized event allowing employees to sell vested shares to an outside buyer before IPO. Provides liquidity in otherwise illiquid private company stock.', 'After 5 years you have 30,000 vested shares. A secondary fund offers $40/share in a tender offer. You sell 10,000 shares ($400K minus taxes), keep 20,000 for IPO upside.', 'Selling too much or too little. Selling everything loses future upside. Selling nothing maintains all risk. A balanced approach is usually optimal.', 'Tender offers are the primary way startup employees get real money before IPO. They can be a once-in-a-career derisk opportunity.', 'Negotiation', ARRAY['secondary-sale', 'ipo', 'cashless-exercise', 'lock-up-period']),

('Secondary Sale', 'secondary-sale', 'Selling private company stock to a third party outside a formal tender offer. Must typically be approved by the board. Platforms like Forge and EquityZen facilitate these transactions.', 'An early employee finds a buyer on a secondary marketplace at $30/share. Board approves the transfer. Employee sells 5,000 shares for $150K minus fees and taxes.', 'Attempting to sell without company approval. Most agreements include transfer restrictions and ROFR. Selling without board approval can violate your agreement.', 'Secondary sales provide liquidity when tender offers are unavailable, but prices often reflect significant discounts to the last round.', 'Negotiation', ARRAY['tender-offer', 'ipo', 'lock-up-period', 'repurchase-rights']),

('IPO (Initial Public Offering)', 'ipo', 'A private company lists shares on a public exchange for the first time. Triggers RSU settlement, enables cashless exercise, and provides the first opportunity for true liquidity, subject to lock-up period.', 'Company IPOs at $25/share. You have 20,000 vested options at $3 strike. After 6-month lock-up, your pre-tax profit: 20,000 x $22 = $440,000.', 'Selling everything when lock-up expires. The period right after expiration often sees a dip as employees sell. A planned selling strategy usually produces better results.', 'An IPO is the most common path to significant equity value. Understanding lock-up, taxes, and selling strategy can make a six-figure difference.', 'Basics', ARRAY['lock-up-period', 'rsu', 'double-trigger', 'cashless-exercise']),

('SPAC', 'spac', 'A shell company that raises money through its own IPO, then merges with a private company to take it public. For employees, a SPAC merger functions similarly to a traditional IPO.', 'Your startup merges with a SPAC. Your 15,000 options at $2 strike convert to options on the public company trading at $12/share.', 'Treating a SPAC merger the same as a quality IPO. SPACs have historically underperformed. Many SPAC companies saw 50-80% stock price declines within a year.', 'If your company goes public via SPAC, understand the higher risk of post-merger decline and potential dilution from SPAC sponsors.', 'Basics', ARRAY['ipo', 'lock-up-period', 'dilution', 'change-of-control']),

('Clawback', 'clawback', 'A provision allowing the company to reclaim equity or proceeds in certain circumstances: termination for cause, non-compete violations, breach of confidentiality, or misconduct.', 'An executive violates a non-compete. The company claws back 50,000 unvested options and demands return of $200K in profits from previously sold shares.', 'Not reading clawback provisions. Many employees skip fine print about triggers. Some agreements have surprisingly broad clawback rights extending years past departure.', 'Clawback provisions can turn equity into a conditional benefit. Understanding triggers prevents inadvertent forfeiture.', 'Negotiation', ARRAY['repurchase-rights', 'exercise-window', 'vesting']),

('Repurchase Rights', 'repurchase-rights', 'The company right to buy back your shares when you leave. For unvested shares (after early exercise): repurchase at cost. Some agreements also allow repurchase of vested shares at FMV.', 'You early-exercised 50,000 shares at $0.10. After 2 years (50% vested), you leave. Company repurchases 25,000 unvested shares at $0.10, returning $2,500. Vested shares are yours.', 'Not checking if the company has repurchase rights on vested shares. Some early-stage companies include this, meaning even vested shares can be bought back.', 'Repurchase rights determine whether leaving means losing equity. Understand these before accepting.', 'Negotiation', ARRAY['early-exercise', 'restricted-stock', 'clawback', 'exercise-window']),

('Double Trigger Acceleration', 'double-trigger', 'Requires two events for accelerated vesting: (1) change of control AND (2) involuntary termination within 12-24 months. Both must occur for unvested equity to vest immediately.', 'Company is acquired (trigger 1). You continue for 8 months, then are laid off (trigger 2). All unvested equity vests. Voluntary resignation would NOT trigger acceleration.', 'Assuming voluntary departure counts as trigger 2. In almost all provisions, you must be involuntarily terminated. Quitting does not trigger acceleration.', 'Double-trigger protects against acqui-hire-and-fire scenarios. The most important protection to have in your equity agreement.', 'Vesting', ARRAY['acceleration', 'single-trigger', 'change-of-control', 'vesting']),

('Single Trigger Acceleration', 'single-trigger', 'Requires only one event — typically a change of control — to trigger immediate vesting. More favorable than double trigger. Usually reserved for executives.', 'You have 40,000 unvested options with single-trigger. Company is acquired. All 40,000 vest immediately regardless of whether you stay.', 'Expecting single-trigger to be standard. It is rare and acquirers dislike it. Expect pushback if negotiating for it.', 'Single-trigger is the gold standard of protection. If you have leverage, it can be the most valuable term in your equity package.', 'Vesting', ARRAY['acceleration', 'double-trigger', 'change-of-control', 'vesting']),

('Change of Control', 'change-of-control', 'An event transferring ownership — typically acquisition, merger, or sale of assets. The key trigger for acceleration provisions. Exact definition varies by agreement.', 'Company A acquires your startup for $500M. This triggers change-of-control provisions in your equity agreement.', 'Assuming your definition matches the legal one. Some agreements narrowly define it to exclude certain transactions. Read the specific language.', 'Change of control determines what happens to your unvested equity. The definition determines which transactions protect you.', 'Negotiation', ARRAY['acceleration', 'double-trigger', 'single-trigger', 'drag-along']),

('Drag-Along Rights', 'drag-along', 'Allows majority shareholders to force minority shareholders to sell in an approved transaction. If investors approve a sale, all shareholders must participate on the same terms.', 'Investors holding 60% approve an acquisition at $15/share. The drag-along forces all shareholders, including employees, to sell at $15. You cannot hold out.', 'Thinking you can refuse to sell. With drag-along rights (standard in most plans), you cannot block a sale. You must sell at the majority-approved price.', 'Drag-along means you have no veto over an exit. Understanding this prevents unrealistic expectations.', 'Negotiation', ARRAY['tag-along', 'change-of-control', 'liquidation-preference']),

('Tag-Along Rights', 'tag-along', 'Gives minority shareholders the right to join a sale by majority shareholders on the same terms. Protects minorities from being left behind in partial sales.', 'A founder sells personal shares at $20/share. Your tag-along rights let you sell proportionally at the same price.', 'Assuming you have tag-along rights. They are usually for investors and founders, rarely included in employee agreements.', 'Tag-along protects you from insiders getting liquidity at good prices while you hold illiquid shares. Rare but valuable for employees.', 'Negotiation', ARRAY['drag-along', 'secondary-sale', 'tender-offer']),

('SAFE (Simple Agreement for Future Equity)', 'safe', 'An investment instrument that converts to equity at a future priced round. Not debt — no interest or maturity. Converts to preferred stock with a discount or valuation cap.', 'Angel puts $100K in a SAFE with $5M cap. At Series A ($20M valuation), the SAFE converts at the $5M cap, giving 4x more shares than the Series A price.', 'Not understanding how SAFEs affect your equity. SAFEs convert at the next round, creating dilution not visible on the current cap table.', 'Ask about outstanding SAFEs and their caps. They represent hidden dilution your share count does not reflect.', 'Valuation', ARRAY['convertible-note', 'pre-money-valuation', 'dilution', 'cap-table']),

('Convertible Note', 'convertible-note', 'Short-term debt that converts to equity at a future round. Has interest rate, maturity date, and creates actual debt. Includes conversion discount and/or valuation cap.', 'Investor lends $200K via note with 5% interest, $10M cap, 20% discount. At Series A ($15M), the note converts at whichever gives more shares: the cap or the discount.', 'Ignoring the maturity date. If no priced round before maturity, the investor can demand repayment, creating a cash crisis. Notes near maturity are a red flag.', 'Like SAFEs, convertible notes represent hidden dilution and create real debt. Understanding them helps assess dilution and financial health.', 'Valuation', ARRAY['safe', 'pre-money-valuation', 'dilution', 'cap-table']),

('Pre-Money Valuation', 'pre-money-valuation', 'Company value immediately before receiving new investment. Pre-money + investment = post-money. Determines how much dilution existing shareholders experience.', 'Startup has $40M pre-money. VC invests $10M. Post-money: $50M. Investor owns 20%. Your existing shares diluted by 20%.', 'Confusing pre-money and post-money. If a recruiter says "valued at $100M" after raising $25M, your shares were valued at $75M pre-money.', 'Pre-money directly determines dilution from each round. It is the correct number for estimating existing share value.', 'Valuation', ARRAY['post-money-valuation', 'dilution', 'cap-table', 'fully-diluted-shares']),

('Post-Money Valuation', 'post-money-valuation', 'Company value after receiving new investment. Post-money = pre-money + investment. This is the headline number in press releases. Divided by total shares gives implied per-share price.', 'Company raises $30M at $120M post-money. Pre-money was $90M. With 12M shares, each is nominally $10. But common shares are worth less due to preferences.', 'Using post-money to value your shares. The headline includes investor protections that inflate preferred share value. Common may be 40-70% of implied per-share price.', 'Post-money is the number you hear most but least accurate for valuing employee equity. Apply common stock discount and subtract preferences.', 'Valuation', ARRAY['pre-money-valuation', 'fmv', 'liquidation-preference']),

('Fully Diluted Shares', 'fully-diluted-shares', 'Total shares if every convertible instrument (options, warrants, SAFEs, notes) were converted. This is the correct denominator for calculating ownership percentage.', 'Company: 8M outstanding + 2M option pool + 1M from SAFE conversion = 11M fully diluted. Your 11,000 shares = 0.1%, not 0.14%.', 'Using only outstanding shares. Many offer letters show shares out of outstanding, not fully diluted. Always ask for the fully diluted count.', 'Fully diluted gives the most realistic ownership picture. Wrong denominator can make equity look 30-50% more valuable.', 'Valuation', ARRAY['cap-table', 'dilution', 'option-pool', 'safe']),

('Option Pool', 'option-pool', 'Shares reserved for future employee grants. Typically 10-20% of fully diluted shares. Created from authorized unissued shares, negotiated during fundraising.', 'Before Series A, investors require a 15% option pool carved from pre-money. The pool funds equity grants to attract employees.', 'Not considering unallocated pool. A 15% pool with only 5% granted means 10% will dilute everyone as future hires get grants.', 'Option pool directly affects your ownership now and future dilution. Understand its size and allocation.', 'Valuation', ARRAY['fully-diluted-shares', 'dilution', 'cap-table', 'stock-options']),

('Phantom Equity', 'phantom-equity', 'A cash bonus plan mirroring equity value without granting actual shares. No ownership transferred, no cap table impact. Cash payments based on company value at specified events.', 'You receive 10,000 phantom units. At acquisition for $20/share, you receive $200,000 cash (minus taxes). You never owned actual shares.', 'Thinking phantom equity equals real equity. No voting rights, no ownership, taxed entirely as ordinary income. Also has counterparty risk.', 'Common at companies that do not want cap table dilution or at LLCs. Understanding it is a cash bonus, not ownership, helps value it correctly.', 'Basics', ARRAY['sar', 'stock-options', 'rsu', 'common-stock']),

('Stock Appreciation Rights (SARs)', 'sar', 'A grant giving you the right to receive cash (or shares) equal to stock appreciation over a set period. Like phantom equity, provides upside without actual ownership. Can be settled in cash or stock.', 'You receive 5,000 SARs with $10 base. Five years later stock is $45. You receive 5,000 x $35 = $175,000 in cash, taxed as ordinary income.', 'Treating SARs as identical to options. SARs have no exercise cost but are taxed as ordinary income. ISOs can qualify for long-term capital gains treatment.', 'SARs eliminate the exercise cost problem while providing similar upside. Increasingly common at late-stage private companies.', 'Basics', ARRAY['phantom-equity', 'stock-options', 'nso', 'cashless-exercise']),

('Employee Stock Purchase Plan (ESPP)', 'espp', 'A benefit letting employees buy company stock at a 15% discount through payroll deductions. Qualified ESPPs have favorable tax treatment. Lookback provisions can increase the effective discount significantly.', 'Stock is $100 at period start, $120 at end. Buy at 85% of the lower: $85/share. Shares worth $120 — a 41% instant gain on your $5,000 contribution.', 'Not participating. The 15% discount plus lookback means ESPPs offer 15-40%+ returns over 6 months with virtually no risk if you sell immediately.', 'ESPPs are one of the most underutilized employee benefits. For public company employees, they provide nearly risk-free returns.', 'Basics', ARRAY['stock-options', 'capital-gains', 'rsu', 'common-stock']),

('Lock-Up Period', 'lock-up-period', 'A restriction (typically 90-180 days after IPO) during which insiders cannot sell shares. Prevents insider selling from crashing the stock price. Standard practice.', 'Company IPOs April 1 with 180-day lock-up. You cannot sell until October 1, regardless of stock price movement.', 'Not planning financially for lock-up. If counting on IPO proceeds, the 6-month delay matters. Stock price at IPO is not guaranteed when lock-up expires.', 'Lock-up creates real risk: stock can move significantly while you cannot act. Do not count on a specific value before you can sell.', 'Negotiation', ARRAY['ipo', 'blackout-period', 'rule-10b5-1', 'tender-offer']),

('Blackout Period', 'blackout-period', 'Recurring periods (2-4 weeks before earnings) when insiders cannot trade company stock. Prevents insider trading based on material non-public information.', 'Company reports earnings February 15. Blackout January 20 to February 17. No option exercises, share sales, or stock transactions during that window.', 'Forgetting blackouts when planning exercises or sales. With four quarterly blackouts lasting 3-4 weeks each, you may only have 8-9 months per year to trade.', 'Blackout periods limit when you can transact. Ignoring them can block time-sensitive tax planning or exercises.', 'Negotiation', ARRAY['lock-up-period', 'rule-10b5-1', 'ipo', 'exercise-window']),

('Rule 10b5-1 Plan', 'rule-10b5-1', 'A pre-established trading plan allowing insiders to sell stock on a predetermined schedule, even during blackouts. Must be set up when not aware of material non-public information.', 'Executive sets up plan in March to sell 1,000 shares monthly for 12 months. Pre-scheduled sales proceed automatically, even during earnings or acquisition talks.', 'Thinking 10b5-1 plans are only for executives. Any insider with access to material non-public information can benefit, including engineers and product managers.', 'A 10b5-1 plan is the best way for public company employees to systematically reduce concentration risk without worrying about blackouts.', 'Negotiation', ARRAY['blackout-period', 'lock-up-period', 'ipo', 'capital-gains']),

('Section 409A', 'section-409a', 'IRS tax code governing deferred compensation including stock options. Requires options be granted at or above FMV. Non-compliant options trigger immediate taxation plus 20% penalty tax.', 'Startup grants at $1/share but actual FMV was $3. IRS determines 409A violation. Each holder owes income tax on the spread plus 20% penalty plus interest.', 'Assuming the company handled 409A correctly. If options are later found below FMV, YOU bear the penalty. Ask whether they have a current 409A from a reputable firm.', '409A violations create serious tax consequences for employees. Verify your employer has proper compliance to protect yourself.', 'Tax', ARRAY['409a-valuation', 'fmv', 'strike-price', 'stock-options']),

('Golden Parachute', 'golden-parachute', 'A contract guaranteeing executives substantial compensation if terminated after a change of control. Includes accelerated vesting, cash severance, continued benefits. Subject to 280G excise tax.', 'CEO has: 2 years salary ($800K), full equity acceleration ($5M), 2 years benefits ($50K), $500K bonus. Total: ~$6.35M if terminated post-acquisition.', 'Thinking golden parachutes are only for the C-suite. VP and director-level employees at well-funded startups often negotiate similar change-of-control provisions.', 'Understanding golden parachutes shows how executives are protected vs rank-and-file. Informs what you can negotiate at senior levels.', 'Negotiation', ARRAY['change-of-control', 'acceleration', 'double-trigger', 'single-trigger']),

('Equity Refresh Grant', 'equity-refresh-grant', 'Additional equity granted to existing employees, typically annually, on top of the initial hire grant. Designed to maintain competitive total compensation and retain high performers.', 'Joined with 10,000 RSUs over 4 years. Year 2 refresh: 3,000 more RSUs. Year 3: 4,000 more. By year 4+, annual vesting from stacked refreshes may exceed initial grant rate.', 'Leaving right after initial grant vests ("4-year cliff"). If receiving competitive refreshes, years 4-6 may have higher annual equity than year 1. Run the numbers before deciding.', 'Refresh grants are the primary long-term retention mechanism. Understanding your company refresh cadence informs stay-vs-leave decisions.', 'Negotiation', ARRAY['rsu', 'vesting', 'stock-options', 'iso']);
